name: Quet_Lich_Lam_Ha_Tu_Dong

on:
  schedule:
    - cron: '0 0 * * *' # Chạy lúc 7h sáng giờ VN
  workflow_dispatch: # Nút bấm chạy tay cho sếp

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install playwright pandas
          playwright install chromium --with-deps

      - name: Run Bot
        run: python main.py
